#!/usr/bin/env bash
# Installs and configures haproxy
apt update
apt install -y haproxy=1.6.\*

cp /etc/haproxy/haproxy.cfg "/etc/haproxy/haproxy.cfg-$(date +%s%N).bak"

cat > /etc/haproxy/haproxy.cfg << "EOF"
frontend http_front
	bind *:80
	default_backend web-backend

backend web-backend
	balance roundrobin
	mode http
	server web1 35.243.194.38:80 check
	server web2 54.91.79.148:80 check
EOF

service haproxy restart
