#!/usr/bin/env bash
# This script creates a backup of all databases and then compresses it using tar
mysqldump -uroot -p"$1" --all-databases > backup.sql 2> /dev/null
tar -czf "$(date +%d-%m-%Y.tar.gz)" backup.sql
