#!/usr/bin/env bash
# This script kills all 'nginx' processes changes the listen port to 80
sudo pkill nginx
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default 
sudo service nginx start
