#!/usr/bin/env bash
# This script displays information related about the `holbertonschool` file

filename="holbertonschool"
if [ -f "$filename" ] || [ -d "$filename" ]
then
	echo "$filename file exists"

	if [ -s "$filename" ]
	then
		echo "$filename file is not empty"

	if [ ! -d "$filename" ]
	then
		echo "$filename is a regular file"
	fi

	else
		echo "$filename file is empty"
	fi

else
	echo "$filename file does not exist"
fi
