#!/usr/bin/env bash
# This script makes nginx server listen on port 8080
sudo pkill apache2
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo su -c 'service nginx start' nginx
